name: Create Release and Tag

on:
  workflow_dispatch: # Manual trigger

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Read version from config.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' config.json)
          echo "Version is $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create and push tag
        run: |
          git tag -a v${{ steps.read_version.outputs.VERSION }} -m "Release version v${{ steps.read_version.outputs.VERSION }}"
          git push origin v${{ steps.read_version.outputs.VERSION }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.read_version.outputs.VERSION }}
          release_name: v${{ steps.read_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: "Release of pkg-go-dev-demo version v${{ steps.read_version.outputs.VERSION }}"

      - name: Go to module directory and tidy up Go modules
        run: |
          go mod tidy
